### ISSUE TITLE
[feat] Add repository to kubesearch

### ISSUE THREAD

**Issue by ismailbay** [pascaliske/infrastructure#1637]
Hi Pascal,

I was looking on kubesearch.dev for `plausible` installations, with no results. Google search led me to your helm chart on artifactHub.

Please consider tagging your repository with `k8s-at-home` and `kubesearch` (https://github.com/whazor/k8s-at-home-search), so others can find and profit from your knowledge 😇.

thx

**Comment by pascaliske** [comment]
Hi @ismailbay,

Didn't know https://kubesearch.dev - sounds like a cool project. I added the `k8s-at-home` top which should be fine for them to include my repository.

Have a nice day 🎉
