### ISSUE TITLE
[feat] Setup `plausible-exporter`

### ISSUE THREAD

**Issue by pascaliske** [pascaliske/infrastructure#531]
~~Waiting for https://github.com/riesinger/plausible-exporter/pull/8. 😊~~

https://charts.pascaliske.dev/charts/plausible-exporter/

**Comment by riesinger** [comment]
Which is now merged 😉

**Comment by pascaliske** [comment]
Yeah, which means I have to do for tonight! 😁

**Comment by pascaliske** [comment]
Closed via https://github.com/pascaliske/infrastructure/commit/99a1600a99a9b98f963f47c48fd956a4a6843cca.
